// ai-time-capsule.js (Updated for Generated Articles)
document.addEventListener('DOMContentLoaded', () => {
    const articlesGrid = document.getElementById('ai-articles-grid');
    const indexDataUrl = 'ai_analyses_index.json'; // New index file name

    async function loadArticles() {
        try {
            const response = await fetch(indexDataUrl);
            if (!response.ok) {
                // If the file doesn't exist yet, it's okay for the first run
                if (response.status === 404) {
                    articlesGrid.innerHTML = '<p>No AI analysis articles generated yet. Please trigger the workflow!</p>';
                    return;
                }
                throw new Error(`HTTP error! status: ${response.status}`);
            }
            const articles = await response.json();
            
            // Sort articles by generated_date (newest first)
            articles.sort((a, b) => new Date(b.generated_date) - new Date(a.generated_date));

            articlesGrid.innerHTML = ''; // Clear loading indicator

            if (articles.length === 0) {
                articlesGrid.innerHTML = '<p>No AI analysis articles found yet. Please trigger the workflow!</p>';
                return;
            }

            articles.forEach(article => {
                const articleCard = document.createElement('div');
                articleCard.className = 'ai-article-card';

                if (article.featured_image) { // Use featured_image for the header image
                    const img = document.createElement('img');
                    img.src = article.featured_image;
                    img.alt = article.title;
                    img.onerror = function() {
                        this.style.display = 'none'; // Hide broken images
                    };
                    articleCard.appendChild(img);
                }

                const contentDiv = document.createElement('div');
                contentDiv.className = 'ai-article-card-content';

                const title = document.createElement('h3');
                const titleLink = document.createElement('a');
                titleLink.href = article.html_path; // Link to the newly generated HTML file
                titleLink.target = "_blank"; 
                titleLink.rel = "noopener noreferrer"; 
                titleLink.textContent = article.title;
                title.appendChild(titleLink);
                contentDiv.appendChild(title);

                const summary = document.createElement('p');
                summary.textContent = article.summary;
                contentDiv.appendChild(summary);

                articleCard.appendChild(contentDiv);

                const metaDiv = document.createElement('div');
                metaDiv.className = 'ai-article-meta';
                metaDiv.innerHTML = `
                    <span>Generated: ${new Date(article.generated_date).toLocaleDateString()}</span>
                    <span>Sources: ${article.original_sources_count}</span>
                `;
                articleCard.appendChild(metaDiv);


                articlesGrid.appendChild(articleCard);
            });

        } catch (error) {
            console.error("Could not load AI analysis articles data:", error);
            articlesGrid.innerHTML = '<p>Error loading AI analysis articles. Please try again later.</p>';
        }
    }

    loadArticles();
});
