# .github/workflows/scrape-ai-articles.yml
# This workflow automates the scraping of AI-related articles using Google Custom Search JSON API
# and synthesizes new content using Google Gemini, then commits them to your GitHub repository.

name: Google Gemini AI Time Capsule Builder

on:
  workflow_dispatch: 
  # schedule:
  #   - cron: '0 12 * * *' # Example: Runs every day at 12:00 PM UTC

jobs:
  build-ai-time-capsule:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Allows the workflow to write to the repository's contents

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Ensures full history is fetched for rebase/merge

      - name: Pull latest changes (before generating new content) # FIX: Moved this step up
        run: |
          git config user.name "GitHub Actions Bot" # Configure bot user
          git config user.email "actions@github.com"
          git pull --rebase origin main # Pull and rebase local changes on top of remote

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests newspaper3k Pillow lxml[html_clean] google-generativeai 

      - name: Create directories if they don't exist
        run: |
          mkdir -p generated_articles
          mkdir -p images/ai_time_capsule

      - name: Run AI analysis generation script # This script will now operate on an up-to-date repo
        run: python generate_ai_analysis.py
        env:
          PYTHONUNBUFFERED: 1
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }} 
          GOOGLE_CSE_ID: ${{ secrets.GOOGLE_CSE_ID }} 

      - name: Commit and push generated changes # Now, only add/commit the new changes and push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # No need for git config here again, already done in 'Pull latest changes' step
          git add generated_articles/ 
          git add ai_analyses_index.json 
          git commit -m "Automated: Added new AI analysis article via Google Gemini." || echo "No changes to commit" 
          git push
