# .github/workflows/scrape-ai-articles.yml
# This workflow automates the scraping of AI-related articles using Google Custom Search JSON API
# and commits them to your GitHub repository for display on GitHub Pages.

name: Google CSE AI Time Capsule Builder

on:
  workflow_dispatch: 
  # schedule:
  #   - cron: '0 12 * * *' # Example: Runs every day at 12:00 PM UTC

jobs:
  build-ai-time-capsule:
    runs-on: ubuntu-latest
    permissions:
      contents: write 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests newspaper3k Pillow lxml[html_clean]

      - name: Create images directory if it doesn't exist
        run: mkdir -p images/ai_time_capsule

      - name: Run AI article scraping script
        run: python scrape_ai_articles.py
        env:
          PYTHONUNBUFFERED: 1
          # Pass the Google API key and CSE ID from GitHub Secrets
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }} 
          GOOGLE_CSE_ID: ${{ secrets.GOOGLE_CSE_ID }} 

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add ai_articles.json images/ai_time_capsule/ 
          git commit -m "Automated: Added new AI Time Capsule articles via Google CSE." || echo "No changes to commit" 
          git push
